export interface Anime {
  id: string;
  name: string;
  image: string;
  genre: string;
}

export interface Genre {
  id: string;
  name: string;
  animes: Anime[];
}

const createAnime = (id: string, name: string, image: string, genre: string): Anime => ({
  id,
  name,
  image,
  genre,
});

export const genres: Genre[] = [
  {
    id: 'acao',
    name: 'Ação',
    animes: [
      createAnime('naruto', 'Naruto Shippuden', 'https://cdn.myanimelist.net/images/anime/1565/111305l.jpg', 'Ação'),
      createAnime('aot', 'Attack on Titan', 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg', 'Ação'),
      createAnime('demon-slayer', 'Demon Slayer', 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg', 'Ação'),
      createAnime('opm', 'One Punch Man', 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg', 'Ação'),
      createAnime('bleach', 'Bleach', 'https://cdn.myanimelist.net/images/anime/3/40451l.jpg', 'Ação'),
      createAnime('black-clover', 'Black Clover', 'https://cdn.myanimelist.net/images/anime/2/88336l.jpg', 'Ação'),
      createAnime('one-piece', 'One Piece', 'https://cdn.myanimelist.net/images/anime/1244/138851l.jpg', 'Ação'),
      createAnime('chainsaw-man', 'Chainsaw Man', 'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg', 'Ação'),
      createAnime('mob-psycho', 'Mob Psycho 100', 'https://cdn.myanimelist.net/images/anime/8/80356l.jpg', 'Ação'),
      createAnime('hellsing', 'Hellsing Ultimate', 'https://cdn.myanimelist.net/images/anime/6/7331l.jpg', 'Ação'),
      createAnime('fate-zero', 'Fate/Zero', 'https://cdn.myanimelist.net/images/anime/2/73249l.jpg', 'Ação'),
      createAnime('samurai-champloo', 'Samurai Champloo', 'https://cdn.myanimelist.net/images/anime/1375/121599l.jpg', 'Ação'),
      createAnime('dororo', 'Dororo', 'https://cdn.myanimelist.net/images/anime/1879/100467l.jpg', 'Ação'),
      createAnime('akame', 'Akame ga Kill!', 'https://cdn.myanimelist.net/images/anime/1429/95946l.jpg', 'Ação'),
      createAnime('fmab', 'Fullmetal Alchemist: Brotherhood', 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg', 'Ação'),
      createAnime('fire-force', 'Fire Force', 'https://cdn.myanimelist.net/images/anime/1091/101153l.jpg', 'Ação'),
    ],
  },
  {
    id: 'romance',
    name: 'Romance',
    animes: [
      createAnime('your-name', 'Your Name', 'https://cdn.myanimelist.net/images/anime/5/87048l.jpg', 'Romance'),
      createAnime('toradora', 'Toradora!', 'https://cdn.myanimelist.net/images/anime/13/22128l.jpg', 'Romance'),
      createAnime('kaguya', 'Kaguya-sama: Love is War', 'https://cdn.myanimelist.net/images/anime/1295/106551l.jpg', 'Romance'),
      createAnime('horimiya', 'Horimiya', 'https://cdn.myanimelist.net/images/anime/1791/110336l.jpg', 'Romance'),
      createAnime('bunny-girl', 'Rascal Does Not Dream of Bunny Girl Senpai', 'https://cdn.myanimelist.net/images/anime/1301/93586l.jpg', 'Romance'),
      createAnime('clannad', 'Clannad: After Story', 'https://cdn.myanimelist.net/images/anime/1299/110774l.jpg', 'Romance'),
      createAnime('plastic-memories', 'Plastic Memories', 'https://cdn.myanimelist.net/images/anime/1347/139329l.jpg', 'Romance'),
      createAnime('golden-time', 'Golden Time', 'https://cdn.myanimelist.net/images/anime/1307/143112l.jpg', 'Romance'),
      createAnime('lovely-complex', 'Lovely Complex', 'https://cdn.myanimelist.net/images/anime/1470/133455l.jpg', 'Romance'),
      createAnime('fruits-basket', 'Fruits Basket', 'https://cdn.myanimelist.net/images/anime/1447/99827l.jpg', 'Romance'),
      createAnime('nisekoi', 'Nisekoi', 'https://cdn.myanimelist.net/images/anime/12/54549l.jpg', 'Romance'),
      createAnime('my-dress-up', 'My Dress-Up Darling', 'https://cdn.myanimelist.net/images/anime/1179/119897l.jpg', 'Romance'),
      createAnime('tsuki-ga-kirei', 'Tsuki ga Kirei', 'https://cdn.myanimelist.net/images/anime/1143/93320l.jpg', 'Romance'),
      createAnime('wotakoi', 'Wotakoi', 'https://cdn.myanimelist.net/images/anime/1807/95603l.jpg', 'Romance'),
      createAnime('quintuplets', 'The Quintessential Quintuplets', 'https://cdn.myanimelist.net/images/anime/1775/109514l.jpg', 'Romance'),
      createAnime('tonikaku', 'TONIKAWA', 'https://cdn.myanimelist.net/images/anime/1902/106094l.jpg', 'Romance'),
    ],
  },
  {
    id: 'terror',
    name: 'Terror',
    animes: [
      createAnime('another', 'Another', 'https://cdn.myanimelist.net/images/anime/4/75509l.jpg', 'Terror'),
      createAnime('parasyte', 'Parasyte', 'https://cdn.myanimelist.net/images/anime/3/73178l.jpg', 'Terror'),
      createAnime('tokyo-ghoul', 'Tokyo Ghoul', 'https://cdn.myanimelist.net/images/anime/5/64449l.jpg', 'Terror'),
      createAnime('elfen-lied', 'Elfen Lied', 'https://cdn.myanimelist.net/images/anime/1741/122074l.jpg', 'Terror'),
      createAnime('promised-neverland', 'The Promised Neverland', 'https://cdn.myanimelist.net/images/anime/1830/118780l.jpg', 'Terror'),
      createAnime('higurashi', 'Higurashi: When They Cry', 'https://cdn.myanimelist.net/images/anime/1440/112585l.jpg', 'Terror'),
      createAnime('corpse-party', 'Corpse Party', 'https://cdn.myanimelist.net/images/anime/9/47413l.jpg', 'Terror'),
      createAnime('shiki', 'Shiki', 'https://cdn.myanimelist.net/images/anime/7/29367l.jpg', 'Terror'),
      createAnime('perfect-blue', 'Perfect Blue', 'https://cdn.myanimelist.net/images/anime/1293/142506l.jpg', 'Terror'),
      createAnime('ghost-hunt', 'Ghost Hunt', 'https://cdn.myanimelist.net/images/anime/9/14413l.jpg', 'Terror'),
      createAnime('mononoke', 'Mononoke', 'https://cdn.myanimelist.net/images/anime/1448/132820l.jpg', 'Terror'),
      createAnime('hell-girl', 'Hell Girl', 'https://cdn.myanimelist.net/images/anime/10/47269l.jpg', 'Terror'),
      createAnime('deadman', 'Deadman Wonderland', 'https://cdn.myanimelist.net/images/anime/4/30123l.jpg', 'Terror'),
      createAnime('blood-c', 'Blood-C', 'https://cdn.myanimelist.net/images/anime/1137/119481l.jpg', 'Terror'),
      createAnime('boogiepop', 'Boogiepop and Others', 'https://cdn.myanimelist.net/images/anime/1554/96295l.jpg', 'Terror'),
      createAnime('uzumaki', 'Uzumaki', 'https://cdn.myanimelist.net/images/anime/1565/139438l.jpg', 'Terror'),
    ],
  },
  {
    id: 'comedia',
    name: 'Comédia',
    animes: [
      createAnime('gintama', 'Gintama', 'https://cdn.myanimelist.net/images/anime/10/73274l.jpg', 'Comédia'),
      createAnime('konosuba', 'KonoSuba', 'https://cdn.myanimelist.net/images/anime/8/77831l.jpg', 'Comédia'),
      createAnime('spy-family', 'Spy x Family', 'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg', 'Comédia'),
      createAnime('grand-blue', 'Grand Blue', 'https://cdn.myanimelist.net/images/anime/1156/94945l.jpg', 'Comédia'),
      createAnime('daily-lives', 'Daily Lives of High School Boys', 'https://cdn.myanimelist.net/images/anime/2/65803l.jpg', 'Comédia'),
      createAnime('saiki-k', 'The Disastrous Life of Saiki K.', 'https://cdn.myanimelist.net/images/anime/3/83773l.jpg', 'Comédia'),
      createAnime('nichijou', 'Nichijou', 'https://cdn.myanimelist.net/images/anime/3/75617l.jpg', 'Comédia'),
      createAnime('asobi', 'Asobi Asobase', 'https://cdn.myanimelist.net/images/anime/1484/93482l.jpg', 'Comédia'),
      createAnime('devil-part-timer', 'The Devil is a Part-Timer!', 'https://cdn.myanimelist.net/images/anime/3/50177l.jpg', 'Comédia'),
      createAnime('hinamatsuri', 'Hinamatsuri', 'https://cdn.myanimelist.net/images/anime/1132/92072l.jpg', 'Comédia'),
      createAnime('prison-school', 'Prison School', 'https://cdn.myanimelist.net/images/anime/3/72844l.jpg', 'Comédia'),
      createAnime('komi', 'Komi Can\'t Communicate', 'https://cdn.myanimelist.net/images/anime/1864/117463l.jpg', 'Comédia'),
      createAnime('aho-girl', 'Aho-Girl', 'https://cdn.myanimelist.net/images/anime/11/86616l.jpg', 'Comédia'),
      createAnime('sakamoto', 'Haven\'t You Heard? I\'m Sakamoto', 'https://cdn.myanimelist.net/images/anime/4/78tried.jpg', 'Comédia'),
      createAnime('mob-psycho-comedy', 'Mob Psycho 100', 'https://cdn.myanimelist.net/images/anime/8/80356l.jpg', 'Comédia'),
      createAnime('way-of-househusband', 'The Way of the Househusband', 'https://cdn.myanimelist.net/images/anime/1539/114645l.jpg', 'Comédia'),
    ],
  },
  {
    id: 'fantasia',
    name: 'Fantasia',
    animes: [
      createAnime('sao', 'Sword Art Online', 'https://cdn.myanimelist.net/images/anime/11/39717l.jpg', 'Fantasia'),
      createAnime('rezero', 'Re:Zero', 'https://cdn.myanimelist.net/images/anime/1522/128039l.jpg', 'Fantasia'),
      createAnime('mushoku', 'Mushoku Tensei', 'https://cdn.myanimelist.net/images/anime/1530/117776l.jpg', 'Fantasia'),
      createAnime('made-in-abyss', 'Made in Abyss', 'https://cdn.myanimelist.net/images/anime/6/86733l.jpg', 'Fantasia'),
      createAnime('frieren', 'Frieren: Beyond Journey\'s End', 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg', 'Fantasia'),
      createAnime('howls-castle', 'Howl\'s Moving Castle', 'https://cdn.myanimelist.net/images/anime/5/75810l.jpg', 'Fantasia'),
      createAnime('magi', 'Magi: The Labyrinth of Magic', 'https://cdn.myanimelist.net/images/anime/11/43523l.jpg', 'Fantasia'),
      createAnime('nanatsu', 'The Seven Deadly Sins', 'https://cdn.myanimelist.net/images/anime/8/65409l.jpg', 'Fantasia'),
      createAnime('grimgar', 'Grimgar of Fantasy and Ash', 'https://cdn.myanimelist.net/images/anime/1909/140959l.jpg', 'Fantasia'),
      createAnime('danmachi', 'Is It Wrong to Pick Up Girls in a Dungeon?', 'https://cdn.myanimelist.net/images/anime/9/72807l.jpg', 'Fantasia'),
      createAnime('konosuba-fantasia', 'KonoSuba', 'https://cdn.myanimelist.net/images/anime/8/77831l.jpg', 'Fantasia'),
      createAnime('goblin-slayer', 'Goblin Slayer', 'https://cdn.myanimelist.net/images/anime/1572/95019l.jpg', 'Fantasia'),
      createAnime('shield-hero', 'The Rising of the Shield Hero', 'https://cdn.myanimelist.net/images/anime/1490/101365l.jpg', 'Fantasia'),
      createAnime('no-game', 'No Game No Life', 'https://cdn.myanimelist.net/images/anime/1074/111944l.jpg', 'Fantasia'),
      createAnime('ancient-magus', 'The Ancient Magus\' Bride', 'https://cdn.myanimelist.net/images/anime/3/88476l.jpg', 'Fantasia'),
      createAnime('violet', 'Violet Evergarden', 'https://cdn.myanimelist.net/images/anime/1795/95088l.jpg', 'Fantasia'),
    ],
  },
  {
    id: 'drama',
    name: 'Drama',
    animes: [
      createAnime('violet-drama', 'Violet Evergarden', 'https://cdn.myanimelist.net/images/anime/1795/95088l.jpg', 'Drama'),
      createAnime('your-lie', 'Your Lie in April', 'https://cdn.myanimelist.net/images/anime/3/67177l.jpg', 'Drama'),
      createAnime('anohana', 'Anohana', 'https://cdn.myanimelist.net/images/anime/5/29855l.jpg', 'Drama'),
      createAnime('steins-gate', 'Steins;Gate', 'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg', 'Drama'),
      createAnime('a-silent-voice', 'A Silent Voice', 'https://cdn.myanimelist.net/images/anime/1122/96435l.jpg', 'Drama'),
      createAnime('erased', 'Erased', 'https://cdn.myanimelist.net/images/anime/10/77957l.jpg', 'Drama'),
      createAnime('march', 'March Comes in Like a Lion', 'https://cdn.myanimelist.net/images/anime/6/82898l.jpg', 'Drama'),
      createAnime('grave-fireflies', 'Grave of the Fireflies', 'https://cdn.myanimelist.net/images/anime/1825/138741l.jpg', 'Drama'),
      createAnime('angel-beats', 'Angel Beats!', 'https://cdn.myanimelist.net/images/anime/10/22061l.jpg', 'Drama'),
      createAnime('rainbow', 'Rainbow', 'https://cdn.myanimelist.net/images/anime/6/27069l.jpg', 'Drama'),
      createAnime('banana-fish', 'Banana Fish', 'https://cdn.myanimelist.net/images/anime/1190/93515l.jpg', 'Drama'),
      createAnime('wolf-children', 'Wolf Children', 'https://cdn.myanimelist.net/images/anime/9/35721l.jpg', 'Drama'),
      createAnime('i-want-eat', 'I Want to Eat Your Pancreas', 'https://cdn.myanimelist.net/images/anime/1374/94104l.jpg', 'Drama'),
      createAnime('welcome-nhk', 'Welcome to the NHK', 'https://cdn.myanimelist.net/images/anime/1083/135807l.jpg', 'Drama'),
      createAnime('barakamon', 'Barakamon', 'https://cdn.myanimelist.net/images/anime/12/62869l.jpg', 'Drama'),
      createAnime('kids-on-slope', 'Kids on the Slope', 'https://cdn.myanimelist.net/images/anime/1/35355l.jpg', 'Drama'),
    ],
  },
  {
    id: 'isekai',
    name: 'Isekai',
    animes: [
      createAnime('overlord', 'Overlord', 'https://cdn.myanimelist.net/images/anime/7/88019l.jpg', 'Isekai'),
      createAnime('slime', 'That Time I Got Reincarnated as a Slime', 'https://cdn.myanimelist.net/images/anime/1069/120065l.jpg', 'Isekai'),
      createAnime('rezero-isekai', 'Re:Zero', 'https://cdn.myanimelist.net/images/anime/1522/128039l.jpg', 'Isekai'),
      createAnime('mushoku-isekai', 'Mushoku Tensei', 'https://cdn.myanimelist.net/images/anime/1530/117776l.jpg', 'Isekai'),
      createAnime('log-horizon', 'Log Horizon', 'https://cdn.myanimelist.net/images/anime/5/84004l.jpg', 'Isekai'),
      createAnime('tanya', 'Saga of Tanya the Evil', 'https://cdn.myanimelist.net/images/anime/5/86373l.jpg', 'Isekai'),
      createAnime('no-game-isekai', 'No Game No Life', 'https://cdn.myanimelist.net/images/anime/1074/111944l.jpg', 'Isekai'),
      createAnime('shield-isekai', 'The Rising of the Shield Hero', 'https://cdn.myanimelist.net/images/anime/1490/101365l.jpg', 'Isekai'),
      createAnime('sao-isekai', 'Sword Art Online', 'https://cdn.myanimelist.net/images/anime/11/39717l.jpg', 'Isekai'),
      createAnime('konosuba-isekai', 'KonoSuba', 'https://cdn.myanimelist.net/images/anime/8/77831l.jpg', 'Isekai'),
      createAnime('gate', 'Gate', 'https://cdn.myanimelist.net/images/anime/8/76223l.jpg', 'Isekai'),
      createAnime('eminence', 'The Eminence in Shadow', 'https://cdn.myanimelist.net/images/anime/1375/121599l.jpg', 'Isekai'),
      createAnime('cautious-hero', 'Cautious Hero', 'https://cdn.myanimelist.net/images/anime/1884/100301l.jpg', 'Isekai'),
      createAnime('arifureta', 'Arifureta', 'https://cdn.myanimelist.net/images/anime/1491/100694l.jpg', 'Isekai'),
      createAnime('grimgar-isekai', 'Grimgar of Fantasy and Ash', 'https://cdn.myanimelist.net/images/anime/1909/140959l.jpg', 'Isekai'),
      createAnime('ascendance', 'Ascendance of a Bookworm', 'https://cdn.myanimelist.net/images/anime/1809/131313l.jpg', 'Isekai'),
    ],
  },
  {
    id: 'shounen',
    name: 'Shounen',
    animes: [
      createAnime('mha', 'My Hero Academia', 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg', 'Shounen'),
      createAnime('dragon-ball', 'Dragon Ball Z', 'https://cdn.myanimelist.net/images/anime/1277/142022l.jpg', 'Shounen'),
      createAnime('jjk', 'Jujutsu Kaisen', 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg', 'Shounen'),
      createAnime('hxh', 'Hunter x Hunter', 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg', 'Shounen'),
      createAnime('naruto-shounen', 'Naruto', 'https://cdn.myanimelist.net/images/anime/1141/142503l.jpg', 'Shounen'),
      createAnime('one-piece-shounen', 'One Piece', 'https://cdn.myanimelist.net/images/anime/1244/138851l.jpg', 'Shounen'),
      createAnime('demon-slayer-shounen', 'Demon Slayer', 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg', 'Shounen'),
      createAnime('bleach-shounen', 'Bleach', 'https://cdn.myanimelist.net/images/anime/3/40451l.jpg', 'Shounen'),
      createAnime('fairy-tail', 'Fairy Tail', 'https://cdn.myanimelist.net/images/anime/5/18179l.jpg', 'Shounen'),
      createAnime('blue-exorcist', 'Blue Exorcist', 'https://cdn.myanimelist.net/images/anime/10/75195l.jpg', 'Shounen'),
      createAnime('soul-eater', 'Soul Eater', 'https://cdn.myanimelist.net/images/anime/1055/128054l.jpg', 'Shounen'),
      createAnime('haikyuu', 'Haikyuu!!', 'https://cdn.myanimelist.net/images/anime/7/76014l.jpg', 'Shounen'),
      createAnime('kuroko', 'Kuroko\'s Basketball', 'https://cdn.myanimelist.net/images/anime/11/50453l.jpg', 'Shounen'),
      createAnime('dr-stone', 'Dr. Stone', 'https://cdn.myanimelist.net/images/anime/1613/102576l.jpg', 'Shounen'),
      createAnime('food-wars', 'Food Wars!', 'https://cdn.myanimelist.net/images/anime/1702/108376l.jpg', 'Shounen'),
      createAnime('assassination', 'Assassination Classroom', 'https://cdn.myanimelist.net/images/anime/5/75639l.jpg', 'Shounen'),
    ],
  },
  {
    id: 'seinen',
    name: 'Seinen',
    animes: [
      createAnime('berserk', 'Berserk', 'https://cdn.myanimelist.net/images/anime/1384/119988l.jpg', 'Seinen'),
      createAnime('vinland', 'Vinland Saga', 'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg', 'Seinen'),
      createAnime('monster', 'Monster', 'https://cdn.myanimelist.net/images/anime/10/18793l.jpg', 'Seinen'),
      createAnime('psycho-pass', 'Psycho-Pass', 'https://cdn.myanimelist.net/images/anime/5/43399l.jpg', 'Seinen'),
      createAnime('ghost-shell', 'Ghost in the Shell', 'https://cdn.myanimelist.net/images/anime/1549/116620l.jpg', 'Seinen'),
      createAnime('cowboy-bebop', 'Cowboy Bebop', 'https://cdn.myanimelist.net/images/anime/4/19644l.jpg', 'Seinen'),
      createAnime('death-parade', 'Death Parade', 'https://cdn.myanimelist.net/images/anime/5/71553l.jpg', 'Seinen'),
      createAnime('gantz', 'Gantz', 'https://cdn.myanimelist.net/images/anime/1077/135911l.jpg', 'Seinen'),
      createAnime('kingdom', 'Kingdom', 'https://cdn.myanimelist.net/images/anime/1376/117192l.jpg', 'Seinen'),
      createAnime('hellsing-seinen', 'Hellsing Ultimate', 'https://cdn.myanimelist.net/images/anime/6/7331l.jpg', 'Seinen'),
      createAnime('parasyte-seinen', 'Parasyte', 'https://cdn.myanimelist.net/images/anime/3/73178l.jpg', 'Seinen'),
      createAnime('black-lagoon', 'Black Lagoon', 'https://cdn.myanimelist.net/images/anime/10/21695l.jpg', 'Seinen'),
      createAnime('ajin', 'Ajin: Demi-Human', 'https://cdn.myanimelist.net/images/anime/13/78508l.jpg', 'Seinen'),
      createAnime('one-punch-seinen', 'One Punch Man', 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg', 'Seinen'),
      createAnime('dorohedoro', 'Dorohedoro', 'https://cdn.myanimelist.net/images/anime/1871/107815l.jpg', 'Seinen'),
      createAnime('golden-kamuy', 'Golden Kamuy', 'https://cdn.myanimelist.net/images/anime/1586/136956l.jpg', 'Seinen'),
    ],
  },
  {
    id: 'escolar',
    name: 'Escolar',
    animes: [
      createAnime('oregairu', 'Oregairu', 'https://cdn.myanimelist.net/images/anime/1212/106867l.jpg', 'Escolar'),
      createAnime('hyouka', 'Hyouka', 'https://cdn.myanimelist.net/images/anime/13/50521l.jpg', 'Escolar'),
      createAnime('classroom-elite', 'Classroom of the Elite', 'https://cdn.myanimelist.net/images/anime/1446/149982l.jpg', 'Escolar'),
      createAnime('k-on', 'K-ON!', 'https://cdn.myanimelist.net/images/anime/10/76120l.jpg', 'Escolar'),
      createAnime('haruhi', 'The Melancholy of Haruhi Suzumiya', 'https://cdn.myanimelist.net/images/anime/1286/112952l.jpg', 'Escolar'),
      createAnime('lucky-star', 'Lucky Star', 'https://cdn.myanimelist.net/images/anime/1871/113287l.jpg', 'Escolar'),
      createAnime('angel-beats-school', 'Angel Beats!', 'https://cdn.myanimelist.net/images/anime/10/22061l.jpg', 'Escolar'),
      createAnime('charlotte', 'Charlotte', 'https://cdn.myanimelist.net/images/anime/12/74683l.jpg', 'Escolar'),
      createAnime('little-busters', 'Little Busters!', 'https://cdn.myanimelist.net/images/anime/13/42671l.jpg', 'Escolar'),
      createAnime('love-chunibyo', 'Love, Chunibyo & Other Delusions', 'https://cdn.myanimelist.net/images/anime/13/46623l.jpg', 'Escolar'),
      createAnime('kokoro-connect', 'Kokoro Connect', 'https://cdn.myanimelist.net/images/anime/5/40439l.jpg', 'Escolar'),
      createAnime('sakurasou', 'The Pet Girl of Sakurasou', 'https://cdn.myanimelist.net/images/anime/4/43643l.jpg', 'Escolar'),
      createAnime('clannad-school', 'Clannad', 'https://cdn.myanimelist.net/images/anime/1804/95033l.jpg', 'Escolar'),
      createAnime('azumanga', 'Azumanga Daioh', 'https://cdn.myanimelist.net/images/anime/1318/93020l.jpg', 'Escolar'),
      createAnime('daily-school', 'Daily Lives of High School Boys', 'https://cdn.myanimelist.net/images/anime/2/65803l.jpg', 'Escolar'),
      createAnime('himouto', 'Himouto! Umaru-chan', 'https://cdn.myanimelist.net/images/anime/6/75151l.jpg', 'Escolar'),
    ],
  },
  {
    id: 'sobrenatural',
    name: 'Sobrenatural',
    animes: [
      createAnime('death-note', 'Death Note', 'https://cdn.myanimelist.net/images/anime/9/9453l.jpg', 'Sobrenatural'),
      createAnime('mob-psycho-super', 'Mob Psycho 100', 'https://cdn.myanimelist.net/images/anime/8/80356l.jpg', 'Sobrenatural'),
      createAnime('jojo', 'JoJo\'s Bizarre Adventure', 'https://cdn.myanimelist.net/images/anime/3/40409l.jpg', 'Sobrenatural'),
      createAnime('noragami', 'Noragami', 'https://cdn.myanimelist.net/images/anime/9/72765l.jpg', 'Sobrenatural'),
      createAnime('blue-exorcist-super', 'Blue Exorcist', 'https://cdn.myanimelist.net/images/anime/10/75195l.jpg', 'Sobrenatural'),
      createAnime('beyond-boundary', 'Beyond the Boundary', 'https://cdn.myanimelist.net/images/anime/12/53445l.jpg', 'Sobrenatural'),
      createAnime('natsume', 'Natsume\'s Book of Friends', 'https://cdn.myanimelist.net/images/anime/1078/134679l.jpg', 'Sobrenatural'),
      createAnime('ghost-stories', 'Ghost Stories', 'https://cdn.myanimelist.net/images/anime/11/46531l.jpg', 'Sobrenatural'),
      createAnime('xxxholic', 'xxxHOLiC', 'https://cdn.myanimelist.net/images/anime/1076/91654l.jpg', 'Sobrenatural'),
      createAnime('mob-psycho-100-2', 'Mob Psycho 100 II', 'https://cdn.myanimelist.net/images/anime/1018/98781l.jpg', 'Sobrenatural'),
      createAnime('jujutsu-super', 'Jujutsu Kaisen', 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg', 'Sobrenatural'),
      createAnime('bakemonogatari', 'Bakemonogatari', 'https://cdn.myanimelist.net/images/anime/11/75274l.jpg', 'Sobrenatural'),
      createAnime('durarara', 'Durarara!!', 'https://cdn.myanimelist.net/images/anime/1801/97572l.jpg', 'Sobrenatural'),
      createAnime('bungo-stray', 'Bungo Stray Dogs', 'https://cdn.myanimelist.net/images/anime/1819/117673l.jpg', 'Sobrenatural'),
      createAnime('dusk-maiden', 'Dusk Maiden of Amnesia', 'https://cdn.myanimelist.net/images/anime/10/39205l.jpg', 'Sobrenatural'),
      createAnime('kekkai-sensen', 'Blood Blockade Battlefront', 'https://cdn.myanimelist.net/images/anime/3/72554l.jpg', 'Sobrenatural'),
    ],
  },
];

export const getAllAnimes = (): Anime[] => {
  return genres.flatMap((genre) => genre.animes);
};

export const searchAnimes = (query: string): Anime[] => {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];
  
  return getAllAnimes().filter((anime) =>
    anime.name.toLowerCase().includes(lowerQuery)
  );
};
